MvcPracticaFinalLinq/Models/ErrorViewModel.cs
namespace MvcPracticaFinalLinq.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcPracticaFinalLinq/Models/Marta.cs
namespace MvcPracticaFinalLinq.Models
{
    public class Marta
    {
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public string imagen { get; set; }
        public string nombreCurso { get; set; }
        public bool quiereSerCapitan { get; set; }
        public DateTime fechaEvento { get; set; }
        public string nombreActividad { get; set; }
    }
}

MvcPracticaFinalLinq/Models/Plantilla.cs
namespace MvcPracticaFinalLinq.Models
{
    public class Plantilla
    {
        public int hospitalcod { get; set; }
        public int salacod { get; set; }
        public int empleadono { get; set; }
        public string apellido { get; set; }
        public string funcion { get; set; }
        public string turno { get; set; }
        public int salario { get; set; }
    }
}

MvcPracticaFinalLinq/Models/ResumenPlantilla.cs
namespace MvcPracticaFinalLinq.Models
{
    public class ResumenPlantilla
    {
        public int Personas { get; set; }
        public int MaximoSalario { get; set; }
        public int SumaSalarios { get; set; }
        public double MediaSalarial { get; set; }
        public List<Plantilla> Empleados { get; set; }
    }
}

MvcPracticaFinalLinq/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcPracticaFinalLinq.Models;

namespace MvcPracticaFinalLinq.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcPracticaFinalLinq/Controllers/MartaController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPracticaFinalLinq.Models;
using MvcPracticaFinalLinq.Repositories;

namespace MvcPracticaFinalLinq.Controllers
{
    public class MartaController : Controller
    {
        RepositoryUsuarios repo;

        public MartaController()
        {
            this.repo = new RepositoryUsuarios();
        }

        public IActionResult Index()
        {
            List<Marta> usuarios = this.repo.GetUsuarios();
            return View(usuarios);
        }
        public IActionResult Details(int idusuario)
        {
            Marta usuario = this.repo.FindUsuario(idusuario);
            return View(usuario);
        }
    }
}

MvcPracticaFinalLinq/Controllers/PlantillaController.cs
using Microsoft.AspNetCore.Mvc;
using MvcPracticaFinalLinq.Models;
using MvcPracticaFinalLinq.Repositories;

namespace MvcPracticaFinalLinq.Controllers
{
    public class PlantillaController : Controller
    {
        private RepositoryPlantilla repo;

        public PlantillaController()
        {
            this.repo = new RepositoryPlantilla();
        }

        public IActionResult Index()
        {
            List<Plantilla> plantillas = this.repo.GetPlantillas();
            if (plantillas == null)
            {
                ViewData["MENSAJE"] = "No existen plantillas";
                return View();
            }
            else
            {
                return View(plantillas);
            }
        }

        public IActionResult Details(int empleadono)
        {
            Plantilla plantilla = this.repo.FindPlantilla(empleadono);
            return View(plantilla);
        }

        public IActionResult Upsert(int empleadono)
        {
            if (empleadono == 0)
            {
                return View();
            }
            else
            {
                Plantilla plantilla = this.repo.FindPlantilla(empleadono);
                return View(plantilla);
            }
        }
        [HttpPost]
        public IActionResult Upsert(int hospitalcod, int salacod, int empleadono, string apellido, string funcion, string turno, int salario)
        {
            this.repo.UpsertPlantilla(hospitalcod, salacod, empleadono, apellido, funcion, turno, salario);
            ViewData["MENSAJEUP"] = "Operación realizada con éxito";
            return View();
        }

        public IActionResult Delete(int empleadono)
        {
            this.repo.DeletePlantilla(empleadono);
            return RedirectToAction("Index");
        }

        public IActionResult BuscadorPlantillas()
        {
            List<string> funciones = this.repo.GetFunciones();
            ViewData["FUNCIONES"] = funciones;
            return View();
        }
        [HttpPost]
        public IActionResult BuscadorPlantillas(string funcion)
        {
            ResumenPlantilla model = this.repo.GetPlantillaFuncion(funcion);
            List<string> funciones = this.repo.GetFunciones();
            ViewData["FUNCIONES"] = funciones;


            if (model == null)
            {
                ViewData["MENSAJE"] = "No existen empleados con funcion '" +
                                        funcion + "'";
                return View();
            }
            else
            {
                return View(model);
            }
        }
    }
}

MvcPracticaFinalLinq/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcPracticaFinalLinq/Views/Marta/Details.cshtml
@model Marta
<h1>Detalles</h1>

<ul class="list-group">
    <li class="list-group-item">Id: @Model.idUsuario</li>
	<li class="list-group-item">Nombre Completo: @Model.nombre @Model.apellidos</li>
	<li class="list-group-item">Correo: @Model.email</li>
	<li class="list-group-item">Imagen: @Model.imagen</li>
	<li class="list-group-item">Actividad: @Model.nombreActividad</li>
	<li class="list-group-item">Fecha: @Model.fechaEvento</li>
	<li class="list-group-item">Quiere ser capitan? @Model.quiereSerCapitan</li>
	<li class="list-group-item">Curso: @Model.nombreCurso</li>

</ul>

MvcPracticaFinalLinq/Views/Marta/Index.cshtml
@model List<Marta>

<h1>Usuarios</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Accion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var usuario in Model)
        {
            <tr>
                <td>@usuario.idUsuario</td>
                <td>@usuario.nombre</td>
                <td>@usuario.apellidos</td>
                <td>
                    <a asp-action="Details" asp-route-idUsuario="@usuario.idUsuario" class="btn btn-primary">Detalles</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcPracticaFinalLinq/Views/Plantilla/BuscadorPlantillas.cshtml
@model ResumenPlantilla
@{
    List<string> funcionesList = ViewData["FUNCIONES"] as List<string>;
}
<form method="post">
    <select name="funcion" class="form-control">
        @foreach (string ofi in funcionesList)
        {
            <option>@ofi</option>
        }
    </select>
    <button class="btn btn-primary">Buscar empleados</button>
</form>

@if (Model != null)
{
    <ul class="list-group">
        <li class="list-group-item list-group-item-secondary">Personas: @Model.Personas</li>
        <li class="list-group-item list-group-item-warning">Maximo salario: @Model.MaximoSalario</li>
        <li class="list-group-item list-group-item-info">Suma salario: @Model.SumaSalarios</li>
        <li class="list-group-item list-group-item-dark">Media salarial: @Model.MediaSalarial</li>
    </ul>
    @if (Model.Empleados != null)
    {
        <table class="table table-active">
            <thead>
                <tr>
                    <th>Hospital</th>
                    <th>Sala</th>
                    <th>Id</th>
                    <th>Apellido</th>
                    <th>Funcion</th>
                    <th>Turno</th>
                    <th>Salario</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Plantilla emp in Model.Empleados)
                {
                    <tr>
                        <td>@emp.hospitalcod</td>
                        <td>@emp.salacod</td>
                        <td>@emp.empleadono</td>
                        <td>@emp.apellido</td>
                        <td>@emp.funcion</td>
                        <td>@emp.turno</td>
                        <td>@emp.salario</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h2 style="color:blue">No existen empleados con ese oficio</h2>
    }
}

MvcPracticaFinalLinq/Views/Plantilla/Details.cshtml
@model Plantilla

<h1>Detalles Plantilla</h1>

<p>
    <a asp-controller="Plantilla" asp-action="Index">Back</a>
</p>
<ul class="list-group">
    <li class="list-group-item">Hospital: @Model.hospitalcod</li>
    <li class="list-group-item">Sala: @Model.salacod</li>
    <li class="list-group-item">Id Empleado: @Model.empleadono</li>
    <li class="list-group-item">Apellido: @Model.apellido</li>
    <li class="list-group-item">Funcion: @Model.funcion</li>
    <li class="list-group-item">Turno: @Model.turno</li>
    <li class="list-group-item">Salario: @Model.salario €</li>
</ul>

MvcPracticaFinalLinq/Views/Plantilla/Index.cshtml
@model List<Plantilla>

<h1>Plantilla Index</h1>
@if (Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Hospital</th>
                <th>Sala</th>
                <th>Id</th>
                <th>Apellido</th>
                <th>Funcion</th>
                <th>Turno</th>
                <th>Salario</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var emp in Model)
            {
                <tr>
                    <td>@emp.hospitalcod</td>
                    <td>@emp.salacod</td>
                    <td>@emp.empleadono</td>
                    <td>@emp.apellido</td>
                    <td>@emp.funcion</td>
                    <td>@emp.turno</td>
                    <td>@emp.salario</td>
                    <td>
                        <a asp-controller="Plantilla" asp-action="Details" asp-route-empleadono="@emp.empleadono" class="btn btn-primary">Details</a>
                        <a asp-controller="Plantilla" asp-action="Upsert" asp-route-empleadono="@emp.empleadono" class="btn btn-warning">Edit</a>
                        <a asp-controller="Plantilla" asp-action="Delete" asp-route-empleadono="@emp.empleadono" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h2>@ViewData["MENSAJE"]</h2>
}

MvcPracticaFinalLinq/Views/Plantilla/Upsert.cshtml
@model Plantilla
<h1>Upsert Plantilla</h1>
@if (Model==null)
{
    <form method="post">
        <label>Hospital</label>
        <input type="text" name="hospitalcod" class="form-control"/>
        <label>Sala</label>
        <input type="text" name="salacod" class="form-control" />
        <label>Empleado</label>
        <input type="text" name="empleadono" class="form-control" />
        <label>Apellido</label>
        <input type="text" name="apellido" class="form-control" />
        <label>Funcion</label>
        <input type="text" name="funcion" class="form-control" />
        <label>Turno</label>
        <input type="text" name="turno" class="form-control" />
        <label>Salario</label>
        <input type="text" name="salario" class="form-control" />
        <button class="btn btn-success">Upsert</button>
    </form>
    <h2>@ViewData["MENSAJEUP"]</h2>
}
else
{

    <form method="post">
        <label>Hospital</label>
        <input type="text" name="hospitalcod" value="@Model.hospitalcod" class="form-control" />
        <label>Sala</label>
        <input type="text" name="salacod" value="@Model.salacod" class="form-control" />
        <label>Empleado</label>
        <input type="text" name="empleadono" value="@Model.empleadono" class="form-control" />
        <label>Apellido</label>
        <input type="text" name="apellido" value="@Model.apellido" class="form-control" />
        <label>Funcion</label>
        <input type="text" name="funcion" value="@Model.funcion" class="form-control" />
        <label>Turno</label>
        <input type="text" name="turno" value="@Model.turno" class="form-control" />
        <label>Salario</label>
        <input type="text" name="salario" value="@Model.salario" class="form-control" />
        <button class="btn btn-success">Upsert</button>
    </form>
    <h2>@ViewData["MENSAJEUP"]</h2>
}

MvcPracticaFinalLinq/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcPracticaFinalLinq</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcPracticaFinalLinq.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcPracticaFinalLinq</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantilla" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantilla" asp-action="Upsert">Upsert</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantilla" asp-action="BuscadorPlantillas">Buscador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marta" asp-action="Index">Marta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MvcPracticaFinalLinq - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>